In [40]:
from notebook import notebookapp
servers = list(notebookapp.list_running_servers())
print(servers)

[{'base_url': '/', 'hostname': 'localhost', 'notebook_dir': '/local/sdd/rz296', 'password': False, 'pid': 20175, 'port': 8889, 'secure': False, 'token': '11ec73395bce433cab547df63a98cea22cefa2a508dec701', 'url': 'http://localhost:8889/'}]

In [3]:
import pandas as pd
import numpy as np

In [4]:
ppmi = pd.read_csv('../datasets/PPMI/beta_post_Funnorm_PPMI_EPICn524final030618.csv')
ppmi

,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,200973410167_R05C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
cg14817997,0.834027,0.849201,0.772995,0.885288,0.772547,0.756429,0.719766,0.775910,0.768914,0.759352,...,0.788239,0.838946,0.845263,0.770405,0.852917,0.783813,0.806930,0.875691,0.661276,0.737917
cg26928153,0.945589,0.948538,0.962199,0.944048,0.926306,0.956061,0.912988,0.955983,0.957120,0.897589,...,0.951206,0.958975,0.957062,0.954738,0.947765,0.958086,0.948044,0.942405,0.954990,0.946272
cg16269199,0.845186,0.911488,0.948206,0.913622,0.778551,0.903924,0.742258,0.934683,0.897787,0.741083,...,0.889774,0.899517,0.908055,0.946297,0.910522,0.895500,0.889243,0.825368,0.913328,0.898812
cg13869341,0.928455,0.885379,0.881643,0.871767,0.771607,0.903789,0.876725,0.893310,0.905738,0.808371,...,0.939357,0.860004,0.869915,0.862361,0.801204,0.867724,0.930523,0.886429,0.809189,0.868601
cg14008030,0.582476,0.536990,0.599218,0.592665,0.522351,0.573422,0.590794,0.616824,0.700732,0.604100,...,0.649126,0.559064,0.597569,0.641305,0.570829,0.642458,0.632344,0.616005,0.596696,0.585895
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
cg00335297,0.217182,0.742256,0.249338,0.219836,0.558082,0.279446,0.679498,0.275671,0.231694,0.723775,...,0.513439,0.573395,0.541802,0.555809,0.571633,0.557060,0.569576,0.277739,0.264204,0.250837
cg02600718,0.244948,0.247742,0.259630,0.234523,0.232085,0.215568,0.317144,0.212171,0.242866,0.283100,...,0.222662,0.275769,0.205165,0.320637,0.205764,0.253164,0.237742,0.235393,0.237195,0.213956
cg10488260,0.273165,0.845816,0.291222,0.310489,0.807002,0.375273,0.435225,0.424114,0.351202,0.284632,...,0.638698,0.819321,0.738471,0.685108,0.703613,0.783698,0.834090,0.297747,0.322537,0.309052
cg07587934,0.781204,0.716938,0.779612,0.817641,0.787682,0.824879,0.741711,0.697579,0.781049,0.822794,...,0.838456,0.833115,0.776516,0.717632,0.761388,0.877309,0.831079,0.793637,0.833413,0.875907
cg16855331,0.539283,0.519672,0.481618,0.510035,0.492530,0.609815,0.481802,0.343867,0.367808,0.469571,...,0.548287,0.475253,0.470009,0.396620,0.427565,0.480035,0.495302,0.490193,0.384947,0.569885

In [5]:
propag_ageing = pd.read_csv('../datasets/PROPAG-AGEING/methylation_propagageing.csv', index_col='ID_REF')
# list(propag_ageing.columns)
propag_ageing = propag_ageing.drop(['Unnamed: 0'], axis=1)
propag_ageing

,X201438350023_R01C01,X201438350023_R03C01,X201438350023_R04C01,X201438350023_R05C01,X201438350023_R06C01,X201438350023_R07C01,X201438350052_R01C01,X201438350052_R02C01,X201438350052_R05C01,X201438350052_R06C01,...,X202995740078_R05C01,X202995740078_R06C01,X202995740078_R07C01,X202995740078_R08C01,X202995740086_R01C01,X202995740086_R04C01,X202995740086_R05C01,X202995740086_R06C01,X202995740086_R07C01,X202995740086_R08C01
ID_REF,,,,,,,,,,,,,,,,,,,,,
cg21870274,0.797067,0.605931,0.730782,0.727246,0.733856,0.816370,0.725466,0.768639,0.782058,0.752456,...,0.612470,0.745360,0.750678,0.730141,0.701641,0.784990,0.621896,0.791403,0.805270,0.797593
cg09499020,0.264879,0.518585,0.220956,0.355061,0.277508,0.353299,0.221494,0.318525,0.313636,0.240648,...,0.228155,0.246794,0.205696,0.267445,0.189799,0.249763,0.336476,0.226000,0.241351,0.267494
cg16535257,0.277931,0.471738,0.241966,0.508105,0.371380,0.337723,0.203839,0.383591,0.348536,0.225257,...,0.230988,0.326582,0.241612,0.254309,0.206012,0.212837,0.494311,0.280269,0.308469,0.368667
cg00168193,0.891043,0.869452,0.887721,0.895402,0.894507,0.871920,0.876004,0.874049,0.862684,0.900217,...,0.836520,0.888991,0.881488,0.849838,0.889427,0.851649,0.896408,0.884844,0.916529,0.883041
cg06325811,0.218686,0.304831,0.208224,0.252522,0.168871,0.166215,0.179846,0.208724,0.205617,0.164461,...,0.224510,0.250433,0.215284,0.203567,0.221526,0.221724,0.199937,0.231084,0.240375,0.200764
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
cg08265308,0.338211,0.371334,0.329202,0.363310,0.356593,0.372119,0.959784,0.957802,0.342791,0.936197,...,0.481905,0.444347,0.975251,0.471873,0.976447,0.491150,0.979743,0.448790,0.469670,0.975101
cg10488260,0.315333,0.317965,0.356948,0.352644,0.352398,0.349336,0.805168,0.739969,0.323022,0.683338,...,0.373133,0.367859,0.763030,0.419255,0.839747,0.405757,0.902550,0.402768,0.357252,0.553329
cg14273923,0.254213,0.252023,0.264805,0.262647,0.275629,0.271955,0.762703,0.619410,0.264195,0.707219,...,0.314656,0.326333,0.768300,0.315643,0.678554,0.307932,0.638683,0.294244,0.320982,0.585755
cg07587934,0.760656,0.855911,0.765594,0.843382,0.790314,0.820366,0.819547,0.742047,0.743929,0.702442,...,0.819448,0.874524,0.722067,0.861921,0.702745,0.762072,0.749422,0.839330,0.879164,0.693731
cg16855331,0.383710,0.461411,0.457510,0.360231,0.336755,0.471196,0.471518,0.463802,0.356453,0.520328,...,0.395179,0.441209,0.382296,0.443635,0.421434,0.510030,0.368019,0.373857,0.491273,0.529708

In [18]:
result = pd.concat([ppmi, propag_ageing], axis=1, join='inner', ignore_index=False)
result = result.rename_axis("Feature")
# result = result.rename_axis("Sample ID", axis="columns")
# result = result.transpose()
result.index.values.size

#Table of the common features used in both datasets

764345

In [19]:
common_genes = result.index.values
common_genes

array(['cg21870274', 'cg09499020', 'cg16535257', ..., 'cg10488260',
       'cg07587934', 'cg16855331'], dtype=object)

In [10]:
del_features = pd.read_csv('../datasets/annot_info.csv')
del_features

,Unnamed: 0,ID_REF,Name,AddressA_ID,AlleleA_ProbeSeq,AddressB_ID,AlleleB_ProbeSeq,Infinium_Design_Type,Next_Base,Color_Channel,...,Chromosome_36,Coordinate_36,SNP_ID,SNP_DISTANCE,SNP_MinorAlleleFrequency,Random_Loci,X,Class,BOP,n.CpG
0,1,cg00000029,cg00000029,40668283,AACTATACTAACRAAAAAATATCCAAAAAACACTAACRTATAAAAA...,NaN,NaN,II,NaN,NaN,...,16,52025613.0,NaN,NaN,NaN,NaN,NaN,ClassA,chr16:53468284-53469209*N_Shore,9.0
1,2,cg00000103,cg00000103,76703527,AACTTAACTTACAACCAATTATCCCAACRATTTCAACTAATAATAT...,NaN,NaN,II,NaN,NaN,...,4,73689050.0,rs16848262;rs146966574;rs61513989,1;23;27,0.024960;0.000200;0.069090,NaN,NaN,ClassD,NaN,NaN
2,3,cg00000109,cg00000109,39798525,CAATACTAACAAACACATATACCCCCCCACAAATCTTAACTTCTAA...,NaN,NaN,II,NaN,NaN,...,3,173398731.0,rs572345338;rs9864492;rs553441475;rs183505630,2;17;23;24,0.000200;0.009784;0.000599;0.003594,NaN,NaN,ClassC,NaN,NaN
3,4,cg00000155,cg00000155,22679178,AATAAAAAACCACTACACCCAACCTAAACATAATAATTAAATATTC...,NaN,NaN,II,NaN,NaN,...,7,2557091.0,rs116384860,0,0.009784,NaN,NaN,ClassC,NaN,NaN
4,5,cg00000158,cg00000158,33624521,AACTAAACATTCCRTATTATTTACTTCAAACTATTCTCATTTTCCC...,NaN,NaN,II,NaN,NaN,...,9,94050376.0,rs78176522;rs80089624,0;38,0.000200;0.012380,NaN,NaN,ClassC,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
867862,866453,ch.21.788740F,ch.21.788740F,82691238,CTAACTCTTCCCTCAAAACAACTACCTCTAAATTACAACTACCAAA...,NaN,NaN,II,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ClassA,chr21:46961668-46963078*S_Shore,7.0
867863,866499,ch.22.17803970R,ch.22.17803970R,96780498,CAACCAAAATTAAAATTAATTCACCAAACCAAACTCAATAACTCAT...,NaN,NaN,II,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ClassA,chr22:19418745-19420237*S_Shelf,1.0
867864,866525,ch.22.30020508R,ch.22.30020508R,85799208,ATCCTCTAACTCTTAACTTAATCTACCCTATAAATTACACCCTAAA...,NaN,NaN,II,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ClassA,chr22:31686636-31687371*S_Shelf,1.0
867865,866926,ch.4.154120390F,ch.4.154120390F,6653827,CAACCAACAACCTCATTTAAACTCTTAAACCTTTAAAAAACAAATC...,NaN,NaN,II,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ClassA,chr4:153897452-153897749*S_Shelf,2.0
867866,867805,ch.X.153018199F,ch.X.153018199F,82690326,TCAACTCTTTCTCCTAAACTATTCCAAAACCTTACAACTAACCTTA...,NaN,NaN,II,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ClassA,chrX:153362568-153363473*S_Shore,1.0

In [11]:
del_features['ID_REF'][0][:2]
# print(del_features['CHR'].unique())
# del_features[(del_features['ID_REF'].str[:2]) == 'cg']
X_chr = del_features[del_features['CHR'] == 'X']
print("Size of sex genes with X_chr:" + str(X_chr.size))
Y_chr = del_features[del_features['CHR'] == 'Y']
print("Size of sex genes with Y_chr:" + str(Y_chr.size))
sex_genes = pd.concat([X_chr, Y_chr])
sex_genes = sex_genes['ID_REF'].values
sex_genes

Size of sex genes with X_chr:976140
Size of sex genes with Y_chr:28611

array(['cg00004031', 'cg00005617', 'cg00006815', ..., 'cg27545697',
       'cg27578568', 'cg27611726'], dtype=object)

In [22]:
impeding_genes = pd.read_table('../datasets/EPIC_probes_to_be_filtered.txt', delim_whitespace=True)
impeding_genes = impeding_genes['EPIC_probes_to_be_filtered'].values
print('Number of common genes:' + str(common_genes.size))
print('Number of impeding genes:' + str(impeding_genes.size))
print('Number of sex genes:' + str(sex_genes.size))

Number of common genes:764345
Number of impeding genes:99360
Number of sex genes:19701
Number of the remaining genes after removing impeding and sex genes: 645284

In [57]:
set1 = set(common_genes.flatten())
set2 = set(sex_genes.flatten())
# print(len(set1))
# # final_genes.size
# set2 = set(impeding_genes.flatten())
# print(len(set2))
# final_genes = set1.difference(set2)
# # final_genes
# print(len(final_genes))
df1 = pd.DataFrame(data=common_genes[:], columns=['Features'])
# print(df1)
df2 = pd.DataFrame(data=impeding_genes[:], columns=['Features'])
# print(df2)
df3 = pd.DataFrame(data=sex_genes[:], columns=['Features'])
print(df3.shape)
res = pd.merge(df1, df3, how='inner', on=['Features'])
print('Number of sex genes used in PPMI is: ' + str(res.shape[0]))
final_genes = np.array(set1.difference(set2))
type(final_genes)

(19701, 1)
Number of sex genes used in PPMI is: 16677

numpy.ndarray

In [107]:
selected_ppmi = ppmi.loc[final_genes]
selected_ppmi = selected_ppmi.transpose()
selected_ppmi.index

Index(['200973410159_R03C01', '200991620021_R01C01', '200991620021_R03C01',
       '200989060105_R03C01', '200989060135_R07C01', '200989060162_R04C01',
       '200973410167_R04C01', '200973410143_R01C01', '200973410143_R06C01',
       '200973410167_R05C01',
       ...
       '200989060089_R02C01', '200989060089_R01C01', '200989060089_R04C01',
       '200973410143_R08C01', '200973410143_R07C01', '200989060089_R03C01',
       '200989060150_R04C01', '200989060150_R05C01', '200989060150_R06C01',
       '200991620049_R08C01'],
      dtype='object', length=524)

In [33]:
# result_temp[result_temp.index=='cg16535257']
# result_temp[result_temp['X201438350023_R01C01']==0.277931]

In [59]:
groups = pd.read_csv('../datasets/PROPAG-AGEING/propag_phenotypes.csv')[['Colname', 'Group']]
groups = groups.dropna()
groups

                  Colname           Group
0    X201438350023_R01C01  CTR_GENERAL_KI
1    X201438350023_R03C01            CENT
2    X201438350023_R04C01     CTR_GENERAL
3    X201438350023_R05C01     CTR_GENERAL
4    X201438350023_R06C01  CTR_GENERAL_KI
..                    ...             ...
453  X202995740078_R08C01     CTR_GENERAL
454  X202995740086_R01C01  CTR_GENERAL_KI
456  X202995740086_R05C01            PD_A
457  X202995740086_R06C01     CTR_GENERAL
459  X202995740086_R08C01     CTR_GENERAL

[409 rows x 2 columns]

In [61]:
cnt = groups.groupby('Group').count()
print(cnt)

                   Colname
Group
CENT                    28
CENT_OS                 19
CTR_GENERAL            132
CTR_GENERAL_KI          70
PD_A                     1
PD_D                    79
PD_TWIN_INCIDENT        60
PD_TWIN_PREVALENT       20

In [62]:
classPD_pro = pd.DataFrame({"Class": ["Control", "PD"],
                          "Number of patients": [0, 0]})
classPD_pro

     Class  Number of patients
0  Control                   0
1       PD                   0

In [66]:
pd.read_csv('../datasets/PPMI/EstimateCellCounts_PPMI_EPICn524final030618.csv')

,Sentrix_position,CD8T,CD4T,NK,Bcell,Mono,Gran
0,200973410159_R03C01,0.098871,0.158745,0.014156,0.050155,0.056538,0.657973
1,200991620021_R01C01,0.052004,0.163162,0.045057,0.047703,0.066119,0.626899
2,200991620021_R03C01,0.092307,0.170316,0.000000,0.084111,0.103215,0.564232
3,200989060105_R03C01,0.145791,0.046767,0.076241,0.052520,0.085288,0.624211
4,200989060135_R07C01,0.017866,0.062666,0.029187,0.026347,0.104616,0.734208
...,...,...,...,...,...,...,...
519,200989060089_R03C01,0.103612,0.124401,0.135060,0.035850,0.119331,0.491491
520,200989060150_R04C01,0.003675,0.170421,0.086015,0.050823,0.084183,0.620211
521,200989060150_R05C01,0.064991,0.108611,0.032823,0.072779,0.093619,0.649436
522,200989060150_R06C01,0.140840,0.089634,0.044094,0.057892,0.083403,0.610717
523,200991620049_R08C01,0.059249,0.116426,0.021142,0.053487,0.134621,0.629855

In [154]:
patinfo = pd.read_csv('../datasets/PPMI/Patient_Status.csv', index_col='PATNO')
# patinfo.sort_values(by='PATNO')
patinfo.index.astype('int64')
patinfo

,RECRUITMENT_CAT,IMAGING_CAT,ENROLL_DATE,ENROLL_CAT,ENROLL_STATUS,DESCRP_CAT,STATUS_DATE
PATNO,,,,,,,
10362,PRODROMA,PRODROMA,NaN,NaN,Excluded,HYP,08/2013
10405,PRODROMA,PRODROMA,NaN,NaN,Excluded,HYP,09/2014
10496,PRODROMA,PRODROMA,NaN,NaN,Excluded,HYP,06/2013
10606,PRODROMA,no image,NaN,NaN,Declined,HYP,08/2013
10662,PRODROMA,PRODROMA,NaN,NaN,Excluded,HYP,06/2014
...,...,...,...,...,...,...,...
92490,PRODROMA,PRODROMA,01/2015,PRODROMA,Enrolled,HYP,01/2015
92516,PRODROMA,PRODROMA,NaN,NaN,Excluded,HYP,11/2014
92560,PRODROMA,PRODROMA,NaN,NaN,Excluded,HYP,06/2014
92834,PRODROMA,PRODROMA,02/2015,PRODROMA,Enrolled,HYP,02/2015
92876,PRODROMA,PRODROMA,NaN,NaN,Excluded,HYP,11/2014

In [197]:
patno = pd.read_csv('../datasets/PPMI/PPMI_Meth_n524_for_LONI030718.txt',  sep="\t", header=None)
patno.columns = ["PATNO", "Sentrix ID", "Sentrix Position"]
patno.drop([0], axis=0, inplace=True)
patno.set_index(pd.to_numeric(patno["PATNO"]), inplace=True)
patno.drop(columns=["PATNO"], inplace=True)
patno

         Sentrix ID Sentrix Position
PATNO
3000   200973410159           R03C01
3001   200991620021           R01C01
3002   200991620021           R03C01
3003   200989060105           R03C01
3004   200989060135           R07C01
...             ...              ...
3570   200973410143           R07C01
3656   200989060089           R03C01
4058   200989060150           R04C01
4059   200989060150           R05C01
4093   200989060150           R06C01

[524 rows x 2 columns]

In [198]:
result = pd.concat([patinfo, patno], axis=1, join='inner', ignore_index=False)[['ENROLL_CAT']]
result.reset_index("PATNO",inplace=True)
ppmi_classes_group = result.groupby('ENROLL_CAT').count()
ppmi_classes_group.index
ppmi_classes_group.rename(columns={"PATNO":"Number of patients"}, inplace=True)
ppmi_classes_group.rename_axis("Classes of patients")
# ppmi_classes_group = ppmi_classes.loc[['HC', 'PD']]
ppmi_classes_group

            Number of patients
ENROLL_CAT
HC                         134
PD                         330
SWEDD                       54

In [214]:
ppmi_labels = result["ENROLL_CAT"].values
patno["ENROLL_CAT"] = ppmi_labels
#ppmi_patinfo contains 524 rows, including SWEDD
ppmi_patinfo = patno
#ppmi_patno_woswedd only contains 420 rows
ppmi_patno_woswedd = patno[patno["ENROLL_CAT"]!="SWEDD"]
#sentrix_position combines two columns to form the index of the big ppmi table
sentrix_position = ppmi_patno_woswedd["Sentrix ID"]+"_"+ppmi_patno_woswedd["Sentrix Position"]
ppmi_patno_woswedd["Sentrix_position"] = sentrix_position
ppmi_patno_woswedd
#Now, we want a new dataframe that contains only Sentrix_position as index and ENROLL_CAT as labels which are to be matched with original ppmi table
ppmi_classes = pd.DataFrame(index=ppmi_patno_woswedd["Sentrix_position"], data={"Category":ppmi_patno_woswedd["ENROLL_CAT"].values})
ppmi_classes

##need to check whether the Sentrix_position index formed here is equal to the original index column in the ppmi data
## need to debug here: Category contains nan values ?????

True

/local/sdd/rz296/miniconda3/envs/partII/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

In [112]:
patno_seq = ppmi_patno_classes.index
sub_patinfo = patinfo.loc[patno_seq]
sub_patinfo

,RECRUITMENT_CAT,IMAGING_CAT,ENROLL_DATE,ENROLL_CAT,ENROLL_STATUS,DESCRP_CAT,STATUS_DATE
PATNO,,,,,,,
3000,HC,HC,02/2011,HC,Enrolled,NaN,02/2011
3001,PD,PD,03/2011,PD,Enrolled,NaN,03/2011
3002,PD,PD,03/2011,PD,Enrolled,NaN,03/2011
3003,PD,PD,04/2011,PD,Enrolled,NaN,04/2011
3004,HC,HC,04/2011,HC,Enrolled,NaN,04/2011
...,...,...,...,...,...,...,...
3565,HC,HC,06/2011,HC,Enrolled,NaN,06/2011
3570,HC,HC,06/2011,HC,Enrolled,NaN,06/2011
4058,PD,PD,07/2012,PD,Enrolled,NaN,07/2012
4059,PD,PD,07/2012,PD,Enrolled,NaN,07/2012
4093,PD,PD,08/2012,PD,Enrolled,NaN,08/2012